feat(eth-contracts): changing eth-contracts naming to smart-contracts
BitGo/smart-contracts pull request #22
Opened 2021-02-10 20:08 UTC by twtaylorbitgo

Ticket: BG-29484

2021-02-12 20:39 UTC, argjv approved these changes

2021-02-12 20:41 UTC, argjv requested changes
Don't you have to upload the `package-lock.json` too?

2021-02-16 22:07 UTC, twtaylorbitgo commented
> Don't you have to upload the `package-lock.json` too?

Yup yup, did this

2021-02-16 23:00 UTC, argjv approved these changes

2021-02-16 23:01 UTC, merged